DROP TABLE IF EXISTS "FILM_GENRE";
DROP TABLE IF EXISTS "USER_FRIEND";
DROP TABLE IF EXISTS "USER_FILM_LIKE";
DROP TABLE IF EXISTS "FRIENDSHIP_STATUS";
DROP TABLE IF EXISTS "FILM";
DROP TABLE IF EXISTS "MPA_RATING";
DROP TABLE IF EXISTS "GENRE";
DROP TABLE IF EXISTS "USERS";

CREATE TABLE "MPA_RATING" (
    "MPA_RATING_ID" INT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    CONSTRAINT "PK_MPA_RATING" PRIMARY KEY ("MPA_RATING_ID"),
    CONSTRAINT "UC_MPA_RATING_NAME" UNIQUE ("NAME")
);

CREATE TABLE "FRIENDSHIP_STATUS" (
    "FRIENDSHIP_STATUS_ID" INT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    CONSTRAINT "PK_FRIEND_STATUS" PRIMARY KEY ("FRIENDSHIP_STATUS_ID"),
    CONSTRAINT "UC_FRIEND_STATUS_NAME" UNIQUE ("NAME")
);

CREATE TABLE "GENRE" (
   "GENRE_ID" INT NOT NULL,
   "NAME" VARCHAR(255) NOT NULL,
   CONSTRAINT "PK_GENRE" PRIMARY KEY ("GENRE_ID"),
   CONSTRAINT "UC_GENRE_NAME" UNIQUE ("NAME")
);

CREATE TABLE "FILM" (
    "FILM_ID" INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "DESCRIPTION" TEXT NOT NULL,
    "RATE" INT NOT NULL,
    "MPA_RATING_ID" INT,
    "RELEASE_DATE" DATE NOT NULL,
    "DURATION" INT NOT NULL,
    CONSTRAINT "PK_FILM" PRIMARY KEY ("FILM_ID"),
    CONSTRAINT "FK_FILM_MPA_RATING_ID" FOREIGN KEY ("MPA_RATING_ID") REFERENCES "MPA_RATING" ("MPA_RATING_ID")
);

CREATE TABLE "USERS" (
   "USER_ID" INT AUTO_INCREMENT NOT NULL,
   "EMAIL" VARCHAR(255) NOT NULL,
   "LOGIN" VARCHAR(255) NOT NULL,
   "NAME" VARCHAR(255) NULL,
   "BIRTHDAY" DATE NOT NULL,
   CONSTRAINT "PK_USER" PRIMARY KEY ("USER_ID"),
   CONSTRAINT "UC_USER_EMAIL" UNIQUE ("EMAIL"),
   CONSTRAINT "UC_USER_LOGIN" UNIQUE ("LOGIN")
);

CREATE TABLE "FILM_GENRE" (
    "FILM_ID" INT NOT NULL,
    "GENRE_ID" INT NOT NULL,
    CONSTRAINT "FK_FILM_GENRE_FILM_ID" FOREIGN KEY ("FILM_ID") REFERENCES "FILM" ("FILM_ID"),
    CONSTRAINT "FK_FILM_GENRE_GENRE_ID" FOREIGN KEY ("GENRE_ID") REFERENCES "GENRE" ("GENRE_ID")
);

CREATE TABLE "USER_FILM_LIKE" (
    "USER_ID" INT NOT NULL,
    "FILM_ID" INT NOT NULL,
    CONSTRAINT "PK_USER_FILM_LIKE" PRIMARY KEY ("USER_ID", "FILM_ID"),
    CONSTRAINT "FK_USER_FILM_LIKE_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID"),
    CONSTRAINT "FK_USER_FILM_LIKE_FILM_ID" FOREIGN KEY ("FILM_ID") REFERENCES "FILM" ("FILM_ID")
);

CREATE TABLE "USER_FRIEND" (
    "USER_ID" INT NOT NULL,
    "FRIEND_ID" INT NOT NULL,
    "FRIENDSHIP_STATUS_ID" INT NOT NULL,
    CONSTRAINT "PK_USER_FRIEND" PRIMARY KEY ("USER_ID", "FRIEND_ID"),
    CONSTRAINT "FK_USER_FRIEND_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID"),
    CONSTRAINT "FK_USER_FRIEND_FRIEND_ID" FOREIGN KEY ("FRIEND_ID") REFERENCES "USERS" ("USER_ID"),
    CONSTRAINT "FK_USER_FRIEND_FRIEND_STATUS_ID" FOREIGN KEY ("FRIENDSHIP_STATUS_ID") REFERENCES "FRIENDSHIP_STATUS" ("FRIENDSHIP_STATUS_ID")
);
